version: '2.9'

services:
  db-1:
    image: mongo
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: blog
    volumes:
      - ./data/db-1-data:/data/db
  db-2:
    image: mongo
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: blog
    volumes:
      - ./data/db-2-data:/data/db
